In [1]:
import numpy as np

In [4]:
a = np.array([1,2,3])
b =  np.array([(1.5,2,3), (4,5,6)], dtype=float)
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]], dtype=float)

In [5]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.ones((2,3,4), dtype=np.int64)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [9]:
d = np.arange(10,25,5)
print(d)

[10 15 20]


In [10]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [12]:
e = np.full((2,2), 7)
print(e)

[[7 7]
 [7 7]]


In [14]:
f = np.eye(2)
g = np.random.random((2,2))
print("identity matrix:",f)
print("random matrix:",g)

identity matrix: [[1. 0.]
 [0. 1.]]
random matrix: [[0.56568027 0.38131804]
 [0.75469282 0.10964926]]


In [17]:
print("Shape:")
print(a.shape, b.shape, c.shape)
print("dimention:")
print(a.ndim, b.ndim, c.ndim)
print("size:")
print(a.size, b.size, c.size)

Shape:
(3,) (2, 3) (2, 2, 3)
dimention:
1 2 3
size:
3 6 12


In [18]:
print(b.dtype)
print(b.dtype.name)
print(b.astype(int))

float64
float64
[[1 2 3]
 [4 5 6]]


In [25]:
print("Addition:",a + b)
print("Subtraction:", a - b)


print(np.add(a,b))
print(np.subtract(a,b))

Addition: [[2.5 4.  6. ]
 [5.  7.  9. ]]
Subtraction: [[-0.5  0.   0. ]
 [-3.  -3.  -3. ]]
[[2.5 4.  6. ]
 [5.  7.  9. ]]
[[-0.5  0.   0. ]
 [-3.  -3.  -3. ]]


In [28]:
print("Multiplication:",np.multiply(b,b))
print("Division:",np.divide(b,b))

Multiplication: [[ 2.25  4.    9.  ]
 [16.   25.   36.  ]]
Division: [[1. 1. 1.]
 [1. 1. 1.]]


In [29]:
print(np.sqrt(a), np.sqrt(b), np.sqrt(c))

[1.         1.41421356 1.73205081] [[1.22474487 1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]] [[[1.22474487 1.41421356 1.73205081]
  [2.         2.23606798 2.44948974]]

 [[1.73205081 1.41421356 1.        ]
  [2.         2.23606798 2.44948974]]]


In [33]:
a.sum()
a.min()
a.max()
a.cumsum()
a.mean()
np.std(b)





np.float64(42.5)